### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [Jpoulter1908/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [ ] I made one initial commit.
2 commits with the message `Initial Commit`
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
`Past tense`

Hey Jeremy! Overall this is a really solid assessment. We want you to make a few tweaks to your class and object files. Remember that we name our classes `singularly` as opposed to `plurally.`
Another thing we want you to change relates to conventions. It doesn't matter to us in Mod-0 if you choose to capitalize your methods or use an underscore to separate the words of the name or even if you want to have spaces. But, we do want you to choose one thing and stick with it for consistency. Please make these adjustments so that your syntax is consistent across all class and object files. One other thing is we want our method /function names to be the same in a class file and an object file that is an instance of that class. If you meant to show the differences as arguments passed to the method/function then we would use syntax such as `fill_container(water)` or `fillContainer(soda)` with the argument passed inside parentheses. If this doesn't make sense then no worries. Just make sure that the methods have the same name across related files. Please update your files and commit the changes with a proper commit message (which you did the majority of the time in this repo). Please make these changes by EOD on Monday, and ping us on slack once you've updated the repo. Thanks Jeremy

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
